---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.4
  - name: centos-5.8

suites:
  - name: default
    run_list:
      - recipe[chef-updater::default]
    attributes:
