name 'chef-updater'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which provides a custom resource for updating Chef Client.'
long_description 'Application cookbook which provides a custom resource for updating Chef Client.'
version '1.2.0'
issues_url 'https://github.com/johnbellone/chef-updater-cookbook/issues'
source_url 'https://github.com/johnbellone/chef-updater-cookbook'

supports 'aix'
supports 'solaris2'
supports 'centos', '>= 5.8'
supports 'redhat', '>= 5.8'
supports 'ubuntu', '>= 12.04'
supports 'fedora'
supports 'windows'

depends 'poise', '~> 2.6'
depends 'chef-sugar', '~> 3.3'
